### ISSUE TITLE
Add a service to obtain the path to an asset

### ISSUE THREAD

**Issue by discordier** [ContaoBlackForest/contao-encore-bundle#4]
When using an legacy html5 template in Contao (eg `be_tinyMCE.html5`), it would be nice to utilize something like the following:
```php
//...
content_css: '<?= System::getContainer()->get('contao-webpack-encore')->asset('web/layout/tinymce.css'); ?>'
//...
```

**Comment by baumannsven** [comment]
Add description how to load versioned assets.

Add to the config.y(a)ml of the project
```yaml
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/web/layout/manifest.json'
```

With the insert tag `asset` you can replaced the version path of your asset:
```html
<link rel="stylesheet" href="{{asset::layout/css/app.css}}">

after replaced the insert tag:
<link rel="stylesheet" href="layout/css/app.27da5e15a046fd820390.css">
```
